### ISSUE TITLE
Code

### ISSUE THREAD

**Issue by yanmengdi123** [mahmoudnafifi/HistoGAN#1]
Can you share the code please? I can't find it from the homepage. thank you！

**Comment by mahmoudnafifi** [comment]
The paper is currently under review. The code will be released upon acceptance.

**Comment by btwbtm** [comment]
Hi, do you mean cvpr2021? Can't wait to see the code :)

**Comment by mahmoudnafifi** [comment]
Just released HistoGAN code.
