### ISSUE TITLE
Could you tell more details of training ReHistoGAN?

### ISSUE THREAD

**Issue by buyi1128** [mahmoudnafifi/HistoGAN#11]
Hi, I implemented ReHistoGAN according to your paper, maybe some details such as when to do the unsample and downsample operation may be different, but the whole network is consistent with paper.  I'm confused with training ReHistoGAN, could you tell me more details of traning, did you train alternatively encoder-decoer and discriminator? did you use path length penalty in ReHistoGAN? did you adopted moving average in ReHistoGAN? if so, could you tell more about this? Thank you.

**Comment by mahmoudnafifi** [comment]
the code of rehistogan is now available.
