### ISSUE TITLE
Rehistogan trained weights download error

### ISSUE THREAD

**Issue by fahadshamshad** [mahmoudnafifi/HistoGAN#13]
Hi, I am not able to download the weights of Universal Histogan. Can you please check the link again? Thanks.

**Comment by mahmoudnafifi** [comment]
I checked the links and they work properly. Could you please share if you get error message to be able to help on this?

**Comment by fahadshamshad** [comment]
I was not able to download due to access restriction by internet provider. I am able to download it now. Thanks.
