### ISSUE TITLE
there are something wrong when i train

### ISSUE THREAD

**Issue by hanruoshui** [mahmoudnafifi/HistoGAN#14]
hello, i'm a newer to github and this project, when i was training, the error occurred as the pic shown below.
i know it's a simple question for you, but im don't know the reason, could you please help me solve the problem?
![QQ截图20211102162145](https://user-images.githubusercontent.com/90961822/139810896-bce45a75-aaca-4888-856b-db31a826c469.png)

**Comment by mahmoudnafifi** [comment]
It looks like it doesn't point to the correct dataset directory. Make sure that the datasets/faces includes training images.
