### ISSUE TITLE
Can't train on my data using a pre-trained model

### ISSUE THREAD

**Issue by Alexasandrovich** [mahmoudnafifi/HistoGAN#16]
Hi! I tried to use the pre-trained "Universal_rehistoGAN_v2" model to train on my data with the same picture resolution to improve the quality of the neural network, but there was a problem "self.GAN.load_state_dict":

Error(s) in loading state_dict for recoloringGAN:
	size mismatch for ED.encoder_blocks.0.conv_res.weight: copying a param with shape torch.Size([36, 18, 1, 1]) from checkpoint, the shape in current model is torch.Size([16, 8, 1, 1]).
	size mismatch for ED.encoder_blocks.0.conv_res.bias: copying a param with shape torch.Size([36]) from checkpoint, the shape in current model is torch.Size([16]).
	size mismatch for ED.encoder_blocks.0.net.0.weight: copying a param with shape torch.Size([36, 18, 3, 3]) from checkpoint, the shape in current model is torch.Size([16, 8, 3, 3]).
	size mismatch for ED.encoder_blocks.0.net.0.bias: copying a param with shape torch.Size([36]) from checkpoint, the shape in current model is torch.Size([16]).
...

I tried adding "strict=False" as described here (https://github.com/pytorch/pytorch/issues/40859), but to no avail. I suspect that the model I loaded and the target model is not identical, so the error raise to inform about mismatches of size, layers.

How to get around this problem? Thanks in advance for the answer

**Comment by mahmoudnafifi** [comment]
You are right. Please make sure to use
 --network_capacity 18 
when training the universal model.

**Comment by Alexasandrovich** [comment]
Thank you!
