### ISSUE TITLE
More neat training

### ISSUE THREAD

**Issue by Alexasandrovich** [mahmoudnafifi/HistoGAN#17]
Hi, Mahmoud! I need to train the network for a specific task - there is one scene, but filmed from two angles. The problem is that there are cases where from one angle the colors in the scene are more saturated than from the other. Does it make sense to practice with reHistoGAN (Universal) or would it be more practical to look at white balance or exposure correction? Thanks in advance for the answer!

**Comment by mahmoudnafifi** [comment]
If the colors of two frames supposed to be similar, I guess you may use traditional color transfer methods — no need for deep learning. Also exposure adjustment is a potential solution.

**Comment by Alexasandrovich** [comment]
> If the colors of two frames supposed to be similar, I guess you may use traditional color transfer methods — no need for deep learning. Also exposure adjustment is a potential solution.

I've looked at a lot of engineering methods that would do color transfer locally throughout the frame, but unfortunately I haven't found anything that works
