### ISSUE TITLE
Normalize image

### ISSUE THREAD

**Issue by yxh6825123** [mahmoudnafifi/HistoGAN#18]
Hello,
The input image seems have no noralized to [0,1] in histoGAN.py, but RGBuvHistBlock clamp the input into [0,1].

**Comment by mahmoudnafifi** [comment]
Thanks for catching this. It looks i did this clamping when i was polishing the code and didn’t notice this issue. 

If you can create a PR to fix this issue that would be great.

**Comment by mahmoudnafifi** [comment]
I checked the code again. Unfortunately, I don't have the environment setup in my current device to test. But, I couldn't catch where the input is not normalized? All inputs should go through the transform function which implicitly normalize images to 0-1 range. Please let me know where exactly you find the (0-255) images to check again.

**Comment by yxh6825123** [comment]
Sorry to reply this late, I checked this code again, I find that I ignore the totensor() function will normalize images to 0-1, so there is no more issures, I will close this.

**Comment by yxh6825123** [comment]
Sorry to reply this late, I checked this code again, I find that I ignore the totensor() function will normalize images to 0-1, so there is no more issures, I will close this.
