### ISSUE TITLE
When will the code be released, we are all looking forward to it. 

### ISSUE THREAD

**Issue by SanjunLiu** [mahmoudnafifi/HistoGAN#2]

**Comment by mahmoudnafifi** [comment]
Thanks for your interest. It will be released soon (mostly in April).

**Comment by babyjia** [comment]
when to release the code?

**Comment by mahmoudnafifi** [comment]
Sorry for the delay. A Colab notebook for our histogram loss is now provided. The rest of our code will be available soon.
