### ISSUE TITLE
Using your code on matlab.

### ISSUE THREAD

**Issue by Edison12300** [mahmoudnafifi/HistoGAN#22]
Hi, I'm a student and I'm trying to implement your GAN network on Matlab. I'm curious that is this possible to be done?
And if it is, is it possible for you to provide the codes for the GAN layers?

Thanks!

**Comment by mahmoudnafifi** [comment]
Hi, I think Matlab recently offers more flexibility in designing and training deep models compared to previous Matlab versions. Regarding the GAN layer specifications, please check supplementary materials and the code for more details. Also, you can find a [Matlab version](https://github.com/mahmoudnafifi/SIIE) of the [histogram layer](https://github.com/mahmoudnafifi/HistoGAN/tree/master/histogram_classes) used in HistoGAN loss .. you may need to modify it a bit to match what is used in the HistoGAN paper. 

Good luck!

**Comment by Edison12300** [comment]
I see. Thanks for answering!
