### ISSUE TITLE
How to get BGU.exe

### ISSUE THREAD

**Issue by svillaza** [mahmoudnafifi/HistoGAN#29]
Hi,

I would like to get the output image whose resolution is equal to the input image's resolution, but I need the executable BGU.exe, How would I get the BGU.exe program?

Thanks in advance for any help.

**Comment by mahmoudnafifi** [comment]
Hi, thanks for your question. 

You need to build it from Matlab and use [this function](https://github.com/mahmoudnafifi/HistoGAN/blob/master/upsampling/BGU.m) as your main function. If you are not using Windows, then make sure to update the Matlab executable program call [here](https://github.com/mahmoudnafifi/HistoGAN/blob/eb1b4fed6257079b10fdf98ed58d4db8b454dc1d/ReHistoGAN/rehistoGAN.py#L1139). Another option to produce output in high resolution is to use [pyramid upsampling](https://github.com/mahmoudnafifi/HistoGAN/blob/master/utils/pyramid_upsampling.py) which is the default option I believe.

**Comment by svillaza** [comment]
Thanks a lot, Mahmoud Afifi, I just tested the pyramid upsampling method.
