### ISSUE TITLE
Trained HistoGAN head for ReHistoGAN and Universal HistoGAN

### ISSUE THREAD

**Issue by Werty18** [mahmoudnafifi/HistoGAN#3]
Hi. Great work. For ReHistoGAN, it has been mentioned in paper that the weights of head are initialized based on a previously trained HistoGAN. Have you tried training from the scratch and any observations (without skip connection and fine-tuning results are in paper)? And have you used the same trained HistoGAN head (trained on face images) for universal HistoGAN? Thanks.

**Comment by mahmoudnafifi** [comment]
I didn't train the HistoGAN head from scratch for domain-specific ReHistoGAN, but it was trained from scratch for the universal ReHistoGAN on 2 million images. Without skip connections, it couldn't get satisfying reconstruction. Keep in mind that I had some limitations in hardware, so maybe things could work in a different way with more capacity.

**Comment by mahmoudnafifi** [comment]
Hi, 

Thank you for your question. 

I didn't train the HistoGAN head from scratch for domain-specific ReHistoGAN, but it was trained from scratch for the universal ReHistoGAN on 2 million images. Without skip connections, it couldn't get satisfying reconstruction. Keep in mind that I had some limitations in hardware, so maybe things could work in a different way with more capacity.
