### ISSUE TITLE
problems for testing rehistoGAN

### ISSUE THREAD

**Issue by z-shijie** [mahmoudnafifi/HistoGAN#31]
Hi,
I want to test rehistoGAN, I have pre-downloaded the model, but when I run it with the statement left in your README file, 

python histoGAN.py --name Faces_histoGAN --generate True --target_his ./target_images/2.jpg --gpu 0

the image is displayed without input. I try to input the image myself, but it fails. What should I do? I look forward to your answer.
Thanks.

ps(What is "--target_his ./target_images/2.jpg".Is it a folder?)

**Comment by mahmoudnafifi** [comment]
Please make sure the model is located in the right location. Check this [issue](https://github.com/mahmoudnafifi/HistoGAN/issues/27) for example.

**Comment by z-shijie** [comment]
Thank you very much for your answer. I have solved the problem.
