### ISSUE TITLE
Getting weird output

### ISSUE THREAD

**Issue by Nerdyvedi** [mahmoudnafifi/HistoGAN#5]
Hi, 
I am not able to replicate the results correctly.

How do I get the final output?

For example,
I used the following code
`python histoGAN.py --name Faces_histoGAN --generate True --target_his ./target_images/1.jpg --gpu 0
`

And got this output which seems to be noise
![generated-1-05-30-2021_10-13-13-ema](https://user-images.githubusercontent.com/23276664/120113316-888b8700-c197-11eb-8d65-402bc834a224.jpg)

How can I use this to generate face samples as shown in the repo?

Thank you

**Comment by mahmoudnafifi** [comment]
It seems either you didn't download the pre-trained model or the path of the model is not correct. You should download the trained model and copy it in `./models/test_histoGAN/model_0.pt` (it doesn't necessarily be 0, it can be any number. The code will take the highest number if more than one model exist).
