### ISSUE TITLE
How to run on custom input?

### ISSUE THREAD

**Issue by Nerdyvedi** [mahmoudnafifi/HistoGAN#6]
Hi, 
I want to run the model on custom faces image. 
I could not find a parameter that takes in input images directory, It always runs the model on fixed input images.

Thanks

**Comment by mahmoudnafifi** [comment]
Hi,

Do you mean to run the model on real face images? If so, the code of this part is not published yet. I am busy with other stuff this month. I will do my best to post it soon.

The currently available code generates samples (for a specific domain) and accepts a target color histogram as input.

**Comment by Nerdyvedi** [comment]
@Nerdyvedi Could you let me know where should I make the changes, I can try and implemeting it on my own and then create a PR?

**Comment by mahmoudnafifi** [comment]
Check Sec. 2.3 in the [paper](https://arxiv.org/abs/2011.11731). You are more than welcome to re-implement it. But just to let you know that the code of this part is already implemented but needs some polish that I am going to do soon before posting.
